### ISSUE TITLE
Different width tables on storage cost page

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/Ploutos#23]
2nd table doesn't look to be within the same div as the above table and plot

![image](https://user-images.githubusercontent.com/45037268/200855923-1b4de476-52cd-45aa-9626-0c7ceb21fa51.png)

**Comment by jethror1** [comment]
same for file type storage page

![image](https://user-images.githubusercontent.com/45037268/200856276-0dfa419a-7756-4c51-9037-5eaffae57efc.png)

**Comment by JasonLing95** [comment]
![Screenshot from 2022-11-14 10-26-49](https://user-images.githubusercontent.com/60819172/201637339-2f7f0224-f705-43ce-b448-e7cbd794e780.png)

**Comment by JasonLing95** [comment]
Addressing the issue #23, the table width has been adjusted for /Storage page to the same width. The last table in /Files are kept longer as it contains more cols than the two previous tables - make sense to be wider in width. 
![Screenshot from 2022-11-22 15-12-37](https://user-images.githubusercontent.com/60819172/203350421-66ec3e9f-1d68-4299-86e0-5847183a0673.png)
![Screenshot from 2022-11-22 15-12-25](https://user-images.githubusercontent.com/60819172/203350433-abf8e523-9099-4d74-be8b-b43ca420091f.png)
