### ISSUE TITLE
Trailing zeros on runtime of leaderboard jobs table

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/Ploutos#24]
![image](https://user-images.githubusercontent.com/45037268/200860603-febe244f-a466-451a-bced-4f23bd5cf786.png)

**Comment by JasonLing95** [comment]
This issue has been solved.
![Screenshot from 2022-11-28 13-32-33](https://user-images.githubusercontent.com/60819172/204290323-38f436d0-ce22-4355-ab62-662a993734a0.png)
