### ISSUE TITLE
Highcharts modules versions

### ISSUE THREAD

**Issue by rklocke** [eastgenomics/Ploutos#26]
Highcharts modules versions need to be versions v10.2 as well as main highcharts.js so that exporting of graphs to images and 'No data to display' messages work.

**Ploutos/Ploutos/dashboard/templates/dashboard/base.html**
`    <script src="{% static 'js/highcharts.js' %}"></script>
    <script src="https://code.highcharts.com/modules/no-data-to-display.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>
`
to

`    <script src="{% static 'js/highcharts.js' %}"></script>
    <script src="https://code.highcharts.com/10.2/modules/no-data-to-display.js"></script>
    <script src="https://code.highcharts.com/10.2/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/10.2/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/10.2/modules/accessibility.js"></script>
`

![image](https://user-images.githubusercontent.com/67269227/200874255-6fcfe922-ea64-4b28-bb36-eb8b5aefb37a.png)
![image](https://user-images.githubusercontent.com/67269227/200874289-847be889-ba83-4e11-8fac-10de04c3d71b.png)

![image](https://user-images.githubusercontent.com/67269227/200874314-9decdc46-f618-4ed7-995a-10c6abf0e1b2.png)
![image](https://user-images.githubusercontent.com/67269227/200874329-d6180c35-6549-4528-93be-c8597399a714.png)

**Comment by jethror1** [comment]
Fixed in #27
