### ISSUE TITLE
Add default table of unfiltered data for compute view

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/Ploutos#28]
Table of data is only displayed on applying a filter, would be good to just show all data in the current plot as default
![image](https://user-images.githubusercontent.com/45037268/201334893-caa87e4f-7af6-4877-bd6e-7364a0157070.png)
![image](https://user-images.githubusercontent.com/45037268/201335026-54e9d041-8189-4652-80b3-7b9059b9b646.png)

**Comment by JasonLing95** [comment]
This seems to already be the case
![oie_Vi5bRdy1nCBg](https://user-images.githubusercontent.com/60819172/203346048-285e862d-1366-4631-8a65-066bff6e614e.png)
![oie_3iHUqXX7inbI](https://user-images.githubusercontent.com/60819172/203346070-39cc3416-4cf3-4694-80cf-750bd6f0cc28.png)
![oie_8XUywN5F3JDi](https://user-images.githubusercontent.com/60819172/203346087-15b3e621-d9c1-40bd-82f5-b0004764d914.png)

**Comment by JasonLing95** [comment]
this should already be in Leaderboard page

**Comment by JasonLing95** [comment]
This has been corrected in recent PR #39
