### ISSUE TITLE
Missing days in db

### ISSUE THREAD

**Issue by Yu-jinKim** [eastgenomics/Ploutos#34]

**Comment by JasonLing95** [comment]
is this regarding the missing data after 24th January 2023?
![Screenshot from 2023-02-04 12-24-26](https://user-images.githubusercontent.com/60819172/216767498-553ef728-1b27-4aa6-9da4-0550328800d7.png)

**Comment by jethror1** [comment]
yeah it was, just added an issue to remember about it whilst you were off

**Comment by JasonLing95** [comment]
Issue due to DNANexus auth token expiring.
